#EDA
SELECT * FROM `bigqueryexport-183608.amazon.products` 
LIMIT 10;

#Column Stats
SELECT DISTINCT id_type FROM `bigqueryexport-183608.amazon.products`;
SELECT DISTINCT PRODUCT_GROUP FROM `bigqueryexport-183608.amazon.products`;
SELECT DISTINCT product_type_name FROM `bigqueryexport-183608.amazon.products`;

SELECT DISTINCT EXTRACT(DATE FROM partition_date) as date_partitioned FROM `bigqueryexport-183608.amazon.products`
ORDER BY date_partitioned DESC;


##EDA to check if path_golden contains seller information
SELECT id,product_group, path_golden FROM `bigqueryexport-183608.amazon.products` 
LIMIT 10;
# No, only asin information


#Try joining with COM
SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, SALES.ASIN, PRODUCT_GROUP, PRODUCT_TYPE_NAME,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,   
FROM (SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, ASIN,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,
FROM
(SELECT MP_SUP_KEY AS SELLER_ID ,purchase_day AS DATE_OF_PURCHASE, amazon_order_id AS AMAZON_ORDER_ID, fulfillment_channel as SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, ASIN,
SUM(ITEM_PRICE * QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id, partition_date ) AS SALES,
SUM(QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY , amazon_order_id, partition_date ) AS ORDERED_UNITS,
ROW_NUMBER() OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id) as rn
FROM `bigqueryexport-183608.amazon.customer_order_metrics`
WHERE EXTRACT(YEAR FROM purchase_date) IN (2022,2023) AND ORDER_STATUS NOT IN ('Pending', 'Cancelled'))
WHERE rn=1
) SALES
INNER JOIN 
(SELECT ID_TYPE, ID AS ASIN, PRODUCT_GROUP, PRODUCT_TYPE_NAME FROM `bigqueryexport-183608.amazon.products`
WHERE id_type='ASIN') PRODUCTS 
ON SALES.ASIN = PRODUCTS.ASIN;

#Change to LEFT joining
SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, SALES.ASIN, PRODUCT_GROUP, PRODUCT_TYPE_NAME,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,   
FROM (SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, ASIN,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,
FROM
(SELECT MP_SUP_KEY AS SELLER_ID ,purchase_day AS DATE_OF_PURCHASE, amazon_order_id AS AMAZON_ORDER_ID, fulfillment_channel as SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, ASIN,
SUM(ITEM_PRICE * QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id, partition_date ) AS SALES,
SUM(QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY , amazon_order_id, partition_date ) AS ORDERED_UNITS,
ROW_NUMBER() OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id) as rn
FROM `bigqueryexport-183608.amazon.customer_order_metrics`
WHERE EXTRACT(YEAR FROM purchase_date) IN (2022,2023) AND ORDER_STATUS NOT IN ('Pending', 'Cancelled'))
WHERE rn=1
) SALES
LEFT JOIN 
(SELECT ID_TYPE, ID AS ASIN, PRODUCT_GROUP, PRODUCT_TYPE_NAME FROM `bigqueryexport-183608.amazon.products`
WHERE id_type='ASIN') PRODUCTS 
ON SALES.ASIN = PRODUCTS.ASIN;


#EDA on one user to understand why getitng null values in pie chart
SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, SALES.ASIN, PRODUCT_GROUP, PRODUCT_TYPE_NAME,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,   
FROM (SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, ASIN,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,
FROM
(SELECT MP_SUP_KEY AS SELLER_ID ,purchase_day AS DATE_OF_PURCHASE, amazon_order_id AS AMAZON_ORDER_ID, fulfillment_channel as SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, ASIN,
SUM(ITEM_PRICE * QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id, partition_date ) AS SALES,
SUM(QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY , amazon_order_id, partition_date ) AS ORDERED_UNITS,
ROW_NUMBER() OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id) as rn
FROM `bigqueryexport-183608.amazon.customer_order_metrics`
WHERE EXTRACT(YEAR FROM purchase_date) IN (2022,2023) AND ORDER_STATUS NOT IN ('Pending', 'Cancelled'))
WHERE rn=1
) SALES
LEFT JOIN 
(SELECT ID_TYPE, ID AS ASIN, PRODUCT_GROUP, PRODUCT_TYPE_NAME FROM `bigqueryexport-183608.amazon.products`
WHERE id_type='ASIN') PRODUCTS 
ON SALES.ASIN = PRODUCTS.ASIN
WHERE SELLER_ID= 'd3727236-53ab-45fc-81a2-bba077c33074';

#Updated join to handle null values of the category
SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, SALES.ASIN, 
IFNULL(PRODUCTS.PRODUCT_GROUP, 'Unknown') AS PRODUCT_GROUP,
IFNULL(PRODUCTS.PRODUCT_TYPE_NAME, 'Unknown') AS PRODUCT_TYPE_NAME,
SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,   
FROM (SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID, ASIN,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS,
FROM
(SELECT MP_SUP_KEY AS SELLER_ID ,purchase_day AS DATE_OF_PURCHASE, amazon_order_id AS AMAZON_ORDER_ID, fulfillment_channel as SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, ASIN,
SUM(ITEM_PRICE * QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id, partition_date ) AS SALES,
SUM(QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY , amazon_order_id, partition_date ) AS ORDERED_UNITS,
ROW_NUMBER() OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id) as rn
FROM `bigqueryexport-183608.amazon.customer_order_metrics`
WHERE EXTRACT(YEAR FROM purchase_date) IN (2022,2023) AND ORDER_STATUS NOT IN ('Pending', 'Cancelled'))
WHERE rn=1
) SALES
LEFT JOIN 
(SELECT ID_TYPE, ID AS ASIN, PRODUCT_GROUP, PRODUCT_TYPE_NAME FROM `bigqueryexport-183608.amazon.products`
WHERE id_type='ASIN') PRODUCTS 
ON SALES.ASIN = PRODUCTS.ASIN;


## SALES DATA THAT WE HAVE USED IN THE DASHBOARD
SELECT SELLER_ID ,DATE_OF_PURCHASE, AMAZON_ORDER_ID,  SALES_FULFILLMENT_CHANNEL, ORDER_STATUS, SALES, ORDERED_UNITS, 
FROM
(SELECT MP_SUP_KEY AS SELLER_ID ,purchase_day AS DATE_OF_PURCHASE, amazon_order_id AS AMAZON_ORDER_ID, fulfillment_channel as SALES_FULFILLMENT_CHANNEL, ORDER_STATUS,
SUM(ITEM_PRICE * QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id, partition_date ) AS SALES,
SUM(QUANTITY) OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY , amazon_order_id, partition_date ) AS ORDERED_UNITS,
ROW_NUMBER() OVER (PARTITION BY PURCHASE_DAY, MP_SUP_KEY, amazon_order_id) as rn
FROM `bigqueryexport-183608.amazon.customer_order_metrics`
WHERE EXTRACT(YEAR FROM purchase_date) IN (2022,2023) AND ORDER_STATUS NOT IN ('Pending', 'Cancelled'))
WHERE rn=1;